# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffb9752c5dce3e765c1533ef65b002b1641860e9ab89f6e984e378ec3554cf2ba20b4e69273ada9786a52945f13235c8bcca42360583a56bed2209f0094fbb28

test:
  secret_key_base: 0b952c1e6f81ba4e4dfe8ba44ace0ea763591361ae4339acaff2b82027f032e1d5357cb560eaa28e8322d9fad9c9c45ee83133492fbe8bc1902222a3fd40b4ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
